M48
; DRILL file {KiCad (6.0.0)} date Fri Nov  8 15:53:30 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-08T15:53:30-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X137.56Y-53.41
X137.56Y-59.19
T2
X82.5Y-30.0
X82.5Y-94.0
X82.5Y-155.5
X139.0Y-30.0
X139.0Y-94.0
X139.0Y-155.5
T0
M30
